version: "3.7"

services:
  api:
    container_name: "grupo_sbf_api"
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app/src
    command: "uvicorn --host 0.0.0.0 --port 8080 main:get_app --reload"
    expose:
      - 8080
