[default]
REST_APPLICATION_NAME='Group SBF APIs'
REST_APPLICATION_DESCRIPTION='Group SBF APIs'
REST_APPLICATION_WORKERS=4
REST_APPLICATION_HOST='127.0.0.1'
REST_APPLICATION_PORT=8080
COIN_DEFAULT='BRL'
COINS_ENABLED=['USD', 'EUR', 'INR']

[development]
REST_APPLICATION_RELOAD=true
REST_APPLICATION_URL_CORS=['localhost', '127.0.0.1']
REST_APPLICATION_LOG_LEVEL='debug'
BASE_URL_SERVICE_QUOTE='http://economia.awesomeapi.com.br/json/last'

[production]
REST_APPLICATION_RELOAD=false
REST_APPLICATION_URL_CORS=['localhost', '127.0.0.1']
REST_APPLICATION_LOG_LEVEL='info'
BASE_URL_SERVICE_QUOTE='http://economia.awesomeapi.com.br/json/last'
